### ISSUE TITLE
Think of Score System

### ISSUE THREAD

**Issue by jasoncta** [jjooyoun/Endless-Running#23]

**Comment by akltom** [comment]
Index	Score
0	1
1	1
2	1
3	1
4	2
5	2
6	2
7	1
8	1
9	1
10	2
11	2
12	3

**Comment by hoduc** [comment]
Done with this : fffbde2dd736d7c7eb34afb69f1be818fc200014

**Comment by hoduc** [comment]
Added Trump wall(Barrier duplicate) : f183c0dab41fc0ddef0144f406b21791a39a984e
